This is Assignment 11 - Richard Nolan

Requirement 3

The main difference between Pandas and NumPy seems to be that NumPy provides a rigid, efficient framework for dealing with arrays, but Pandas provides more useful tools for "data munging" like the ability to label data and to work around missing data in a fashion that NumPy can't. Pandas is an expansion on NumPy, so they do share similar cores, but Pandas does notably include Data Frames as well, a tool that incorporates data labels and other features into a multidimensional array.

Requirement 4

In [86]:
##Module Import
import numpy as np
import pandas as pd

##Panda Series
bill_names = pd.Series(['Washington', 'Lincoln', 'Hamilton', 'Jackson'],
                 index=['1', '5', '10', '20'])

print(bill_names)

1     Washington
5        Lincoln
10      Hamilton
20       Jackson
dtype: object


Requirement 5

In [87]:
##Series as Dictionary
beverages_dict = {'Dasani': 'A public scam',
                   'Mtn Dew': 'Delicious, yet teeth-rotting',
                   'Bud Heavy': 'Cheap, yet filling',
                   'Earl Grey': 'Soothing late night cuppa',
                   'White Claw': "Ain't no laws with this one"}
beverages = pd.Series(beverages_dict)

##Slicing for One and Many
print(beverages['Bud Heavy'])
print(beverages['Earl Grey':'White Claw'])

Cheap, yet filling
Earl Grey       Soothing late night cuppa
White Claw    Ain't no laws with this one
dtype: object


Requirement 6

In [88]:
##City Proper population dict
population_dict = {'Chongquing': 15872000,
                   'Shanghai': 27058000,
                   'Tokyo': 13929280,
                   'Moscow': 12506468,
                   'Mexico City': 8918653,
                   'London': 9304000,
                   'New York': 8336817}
population = pd.Series(population_dict)

print(population)

Chongquing     15872000
Shanghai       27058000
Tokyo          13929280
Moscow         12506468
Mexico City     8918653
London          9304000
New York        8336817
dtype: int64


Requirement 7

In [89]:
##City Proper population dict
city_country_dict = {'Chongquing': 'China',
                   'Shanghai': 'China',
                   'Tokyo': 'Japan',
                   'Moscow': 'Russia',
                   'Mexico City': 'Mexico',
                   'London': 'Great Britain',
                   'New York': 'United States'}
city_country = pd.Series(city_country_dict)

print(country)

Chongquing             China
Shanghai               China
Tokyo                  Japan
Moscow                Russia
Mexico City           Mexico
London         Great Britain
New York       United States
dtype: object


Requirement 8

In [90]:
##DataFrame
city_dataframe = pd.DataFrame({'population': population,
                       'Country': city_country})

##.index property
print(city_dataframe.index)

##.columns property
print(city_dataframe.columns)

##.keys() method
print(city_dataframe.keys())

Index(['Chongquing', 'Shanghai', 'Tokyo', 'Moscow', 'Mexico City', 'London',
       'New York'],
      dtype='object')
Index(['population', 'Country'], dtype='object')
Index(['population', 'Country'], dtype='object')


Requirement 9

In [91]:
##Series Object
my_pd_series = pd.Series([4, 5, 6, 8],
                 index=['Alpha', 'Beta', 'Gamma', 'Delta'])

##Modifying a value
my_pd_series['Gamma'] = 7
print(my_pd_series)

##Slicing by Explicit Index
print(my_pd_series['Alpha':'Gamma'])

##Slicing by implicit index
print(my_pd_series[1:2])

##Masking
print(my_pd_series[(my_pd_series > 4) & (my_pd_series < 7)])

##Fancy indexing
print(my_pd_series[['Beta','Delta']])

##loc[]
print(my_pd_series.loc['Beta'])

##iloc[]
print(my_pd_series.iloc[1])



Alpha    4
Beta     5
Gamma    7
Delta    8
dtype: int64
Alpha    4
Beta     5
Gamma    7
dtype: int64
Beta    5
dtype: int64
Beta    5
dtype: int64
Beta     5
Delta    8
dtype: int64
5
5


Requirement 10

In [92]:
##Access Column via indxing
print(city_dataframe['population'])

##Access via column names
print(city_dataframe.Country)

##New Column
altitude_dict = {'Chongquing': 801,
                   'Shanghai': 13,
                   'Tokyo': 131,
                   'Moscow': 2579,
                   'Mexico City': 7382,
                   'London': 36,
                   'New York': 33}
altitude = pd.Series(altitude_dict)

city_dataframe.insert(0, 'altitude', altitude)

print(city_dataframe)

Chongquing     15872000
Shanghai       27058000
Tokyo          13929280
Moscow         12506468
Mexico City     8918653
London          9304000
New York        8336817
Name: population, dtype: int64
Chongquing             China
Shanghai               China
Tokyo                  Japan
Moscow                Russia
Mexico City           Mexico
London         Great Britain
New York       United States
Name: Country, dtype: object
             altitude  population        Country
Chongquing        801    15872000          China
Shanghai           13    27058000          China
Tokyo             131    13929280          Japan
Moscow           2579    12506468         Russia
Mexico City      7382     8918653         Mexico
London             36     9304000  Great Britain
New York           33     8336817  United States


Requirement 11

In [93]:
##Series + to make NaN
bob = pd.Series([3, 6, 8], index=[2, 3, 4])
tom = pd.Series([4, 7, 9], index=[3, 4, 5])
print(bob + tom)

##.add method
bob.add(tom, fill_value=0)


2     NaN
3    10.0
4    15.0
5     NaN
dtype: float64


2     3.0
3    10.0
4    15.0
5     9.0
dtype: float64

Requirement 12

In [94]:
##Dataframes
rng = np.random.RandomState(42)
mike = pd.DataFrame(rng.randint(0, 40, (2, 2)),
                 columns=list('DE'))

marl = pd.DataFrame(rng.randint(0, 15, (3, 3)),
                 columns=list('EDF'))

print(mike + marl)

##.add method
fill = mike.stack().mean()
mike.add(marl, fill_value = fill)

      D     E   F
0  42.0  40.0 NaN
1  16.0  16.0 NaN
2   NaN   NaN NaN


D      E      F
0  42.00  40.00  27.75
1  16.00  16.00  27.75
2  31.75  31.75  28.75

Requirement 13

In [95]:
##2d Array
A = rng.randint(5, 10, size=(4, 4))

##Subtraction
print(A-A[0])

[[ 0  0  0  0]
 [-3  0 -1 -1]
 [ 0 -3  1 -3]
 [ 0  0 -2 -4]]


Requirement 14

In [96]:
##Dataframe
df = pd.DataFrame(A, columns=list('QRST'))

##Subtraction
print(df - df.iloc[1])

   Q  R  S  T
0  3  0  1  1
1  0  0  0  0
2  3 -3  2 -2
3  3  0 -1 -3


Requirement 15

The two sentinel values used by Pandas are NaN and None. NaN, an acronym for 'Not a Number,' is used to represent missing numerical data, while None is used to represent a missing object in an array of objects. None can't cross between values, while Nan will 'infect' other values and override them with a NaN.

Requirement 16

In [97]:
##Timing objects and integers
for dtype in ['object', 'int']:
    print("Example time type =", dtype)
    %timeit np.arange(1E6, dtype=dtype).sum()
    print()

Example time type = object
50.7 ms ± 349 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

Example time type = int
2.15 ms ± 20.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



Requirement 17

In [98]:
##.isnull test
ramp = pd.Series([3, np.nan, 'potato', None])

ramp.isnull()

0    False
1     True
2    False
3     True
dtype: bool

Requirement 18

In [99]:
##Dataframe
french_fry = pd.DataFrame([[5,      np.nan, 3],
                           [4,      3,      2],
                           [np.nan, 4,      7]])

##Demonstrations
print(french_fry.dropna())
print(french_fry.dropna(axis = 1))
print(french_fry.dropna(how = 'all'))
print(french_fry.dropna(axis = 1, how = 'all'))
print(french_fry.fillna(0))
print(french_fry.fillna(method='ffill'))
print(french_fry.fillna(method='bfill'))



     0    1  2
1  4.0  3.0  2
   2
0  3
1  2
2  7
     0    1  2
0  5.0  NaN  3
1  4.0  3.0  2
2  NaN  4.0  7
     0    1  2
0  5.0  NaN  3
1  4.0  3.0  2
2  NaN  4.0  7
     0    1  2
0  5.0  0.0  3
1  4.0  3.0  2
2  0.0  4.0  7
     0    1  2
0  5.0  NaN  3
1  4.0  3.0  2
2  4.0  4.0  7
     0    1  2
0  5.0  3.0  3
1  4.0  3.0  2
2  NaN  4.0  7


Requirement 19

In [100]:
##Setup
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)

##From_Tuples
index = pd.MultiIndex.from_tuples(index)
print(index)

##.reindex
pop = pop.reindex(index)
print(pop)

##.unstack
pop_df = pop.unstack()
print(pop_df)

##.stack
print(pop_df.stack())

##indexing and slicing
print(pop[:, 2000])
print(pop[pop > 22000000])

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64
                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64
California    33871648
New York      18976457
Texas         20851820
dtype: int64
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64


Requirement 20

In [101]:
##Series
motorcycle = pd.Series(['Ninja', 'Fury', 'Softtail'], index=['Kawasaki', 'Honda', 'HD'])
automobile = pd.Series(['Civic', 'Corolla', 'Ranger'], index=['Honda', 'Toyota', 'Ford'])

##Concat
pd.concat([motorcycle, automobile])

Kawasaki       Ninja
Honda           Fury
HD          Softtail
Honda          Civic
Toyota       Corolla
Ford          Ranger
dtype: object

Requirement 21

In [102]:
##.append method
df.append(french_fry)

Q    R    S    T    0    1    2
0  9.0  8.0  7.0  9.0  NaN  NaN  NaN
1  6.0  8.0  6.0  8.0  NaN  NaN  NaN
2  9.0  5.0  8.0  6.0  NaN  NaN  NaN
3  9.0  8.0  5.0  5.0  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  5.0  NaN  3.0
1  NaN  NaN  NaN  NaN  4.0  3.0  2.0
2  NaN  NaN  NaN  NaN  NaN  4.0  7.0

Requirement 22

In [103]:
##Dataframes
HR1 = pd.DataFrame({'employee': ['Dick', 'Luke', 'Lisa', 'Sue'],
                    'group': ['Austin', 'Dallas', 'Houston', 'Waco']})
HR2 = pd.DataFrame({'employee': ['Lisa', 'Dick', 'Luke', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})

##One to One
HR3 = pd.merge(HR1, HR2)
print(HR3)

##Many to One
HR4 = pd.DataFrame({'group': ['Austin', 'Dallas', 'Houston'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

print(pd.merge(HR3, HR4))

##Many to Many
HR5 = pd.DataFrame({'group': ['Austin', 'Austin',
                              'Dallas', 'Dallas', 'Waco', 'Waco'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                               'spreadsheets', 'organization']})

print(pd.merge(HR1, HR5))

  employee    group  hire_date
0     Dick   Austin       2008
1     Luke   Dallas       2012
2     Lisa  Houston       2004
3      Sue     Waco       2014
  employee    group  hire_date supervisor
0     Dick   Austin       2008      Carly
1     Luke   Dallas       2012      Guido
2     Lisa  Houston       2004      Steve
  employee   group        skills
0     Dick  Austin          math
1     Dick  Austin  spreadsheets
2     Luke  Dallas        coding
3     Luke  Dallas         linux
4      Sue    Waco  spreadsheets
5      Sue    Waco  organization


Requirement 23

In [104]:
##Merge On
print(pd.merge(HR1, HR2, on ='employee'))

##Merge Left/Right On
HR6 = pd.DataFrame({'name': ['Dick', 'Luke', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})

print(pd.merge(HR1, HR6, left_on="employee", right_on="name").drop('name', axis=1))

##Merge L/R index
HR1a = HR1.set_index('employee')
HR2a = HR2.set_index('employee')

print(pd.merge(HR1a, HR2a, left_index=True, right_index=True))

  employee    group  hire_date
0     Dick   Austin       2008
1     Luke   Dallas       2012
2     Lisa  Houston       2004
3      Sue     Waco       2014
  employee    group  salary
0     Dick   Austin   70000
1     Luke   Dallas   80000
2     Lisa  Houston  120000
3      Sue     Waco   90000
            group  hire_date
employee                    
Dick       Austin       2008
Luke       Dallas       2012
Lisa      Houston       2004
Sue          Waco       2014


Requirement 24

I felt like the addition of Pandas really streamlined the use of Numpy for me, and working through the various uses of Series and Dataframes made a lot of sense for me. In many ways, it seemed like just a tweaking of the Numpy procedures. I'm really curious how we'll be using this moving forward.